config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateUserView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

templates/partials/footer.html
<footer>
        &copy;Nbnb
</footer>

templates/partials/header.html
<header>
    <a href="{% url 'core:home' %}">Nbnb</a>
    
    <ul class="font-extrabold">
        {% if user.is_authenticated %}
        <li><a href="{% url 'users:logout' %}">Log out</a></li>
        <li><a href="{{ user.get_absolute_url }}">Profile</a></li>
        {% else %}      
        <li><a href="{% url 'users:login' %}">Log in</a></li>
        <li><a href="{% url 'users:signup' %}">Sign up</a></li>
        {% endif %}
        
    </ul>
        
    </header>