config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "rooms"


urlpatterns = [
    path("<int:pk>", room_views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", room_views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", room_views.Photos.as_view(), name="photos"),
]

rooms/models.py
from audioop import reverse as audido_reverse
from django.urls import reverse
from django.db import models
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models

# import reviews


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class RoomType(AbstractItem):

    """Room Type Model Definition"""

    class Meta:
        verbose_name_plural = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):

    """Amenity Object Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """House Rule Model Definition"""

    class Meta:
        verbose_name_plural = "House Rules"


class Room(core_models.TimeStampedModel):

    """Room Model Definitiion"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=100)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    max_guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, on_delete=models.CASCADE, related_name="rooms"
    )

    room_type = models.ForeignKey(
        RoomType, on_delete=models.SET_NULL, null=True, related_name="rooms"
    )
    amenities = models.ManyToManyField(Amenity, blank=True, related_name="rooms")
    facilities = models.ManyToManyField(Facility, blank=True, related_name="rooms")
    house_rules = models.ManyToManyField(HouseRule, blank=True, related_name="rooms")

    def get_absolute_url(self):
        return reverse("rooms/room_detail.html", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) != 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        else:
            return 0


class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photo")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="photos")

    def __str__(self):
        return self.caption

rooms/views.py
from django.views.generic import ListView, DetailView, UpdateView
from django.utils import timezone
from django.http import Http404
from . import models as room_models


# Create your views here.


class HomeView(ListView):

    """HomeView Definition"""

    model = room_models.Room
    paginate_by = 10
    paginate_orphans = 5
    page_kwarg = "page"
    ordering = "pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context


class RoomDetail(DetailView):

    """Room Detail Definition"""

    model = room_models.Room


class EditRoomView(UpdateView):

    """Room Edit View Definition"""

    template_name = "rooms/room_edit.html"
    model = room_models.Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "max_guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "host",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset)
        # if room.host.pk != self.request.user.pk:
        #     raise Http404

        return room


class Photos(DetailView):
    model = room_models.Room
    template_name = "rooms/room_photos.html"

templates/rooms/room_detail.html
{% extends 'base.html' %}

{% block page_title %}Room Details{% endblock page_title %}





{% block content %}

<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
    <h4> By {{room.host.username}}
        {% if room.host.superhost %}(superhost){% endif %}
    </h4>
</div>
<div>
    <h2><a href="{% url 'rooms:edit' room.pk %}">Edit Room</a></h2>
    <h5><a href="{% url 'rooms:photos' room.pk %}">Edit Photos</a></h5>
    <h3>Room Type</h3>
    <ul>
        <li>{{room.room_type}}</li>
    </ul>
    <h3>Amenities</h3>
    <ul>
        {% for a in room.amenities.all %}
        <li>{{a}}</li>
        {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
        {% for f in room.facilities.all %}
        <li>{{f}}</li>
        {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
        {% for f in room.house_rules.all %}
        <li>{{f}}</li>
        {% endfor %}
    </ul>
</div>


{% endblock content %}

templates/rooms/room_edit.html
Hello World!


<form>

    <ul>
        {% for field in form %}
        <li>{{field}}</li>
        {% endfor %}
    </ul>

</form>

templates/rooms/room_list.html
{% extends 'base.html' %}

{% block page_title %}Rooms{% endblock page_title %}





{% block content %}

    {{now}}



    {% for room in object_list %}
        <h2>
            <a href="{% url "rooms:detail" room.pk %}">
                {{room.name}} / ${{room.price}}
            </a>
        </h2>
    {% endfor %}

    <h5>
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}

        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} pages
        
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}

    </h5>



{% endblock content %}

templates/rooms/room_photos.html
{% for photo in room.photos.all %}


<div>
    <img src="{{photo.file.url}}" width="50" height="50">
    <span>{{photo.caption}}</span>
    <button>Edit Photo</button>
    <button>Delete Photo</button>
</div>
{% endfor %}