config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateUserView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Create your models here.

# db 모델 설정


class User(AbstractUser):

    """Custom User Model"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREAN = "kr"

    LANGUAGE_CHOICES = ((LANGUAGE_ENGLISH, "English"), (LANGUAGE_KOREAN, "Korean"))

    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"

    CURRENCY_CHOICES = ((CURRENCY_USD, "USD"), (CURRENCY_KRW, "KRW"))

    bio = models.TextField(default="", blank=True)
    avatar = models.ImageField(blank=True, upload_to="avatars")
    gender = models.CharField(
        max_length=10, choices=GENDER_CHOICES, default="Female", blank=True
    )
    birthdate = models.DateField(blank=True, null=True)
    language = models.CharField(
        choices=LANGUAGE_CHOICES, max_length=10, blank=True, default=LANGUAGE_KOREAN
    )
    currency = models.CharField(
        max_length=3, choices=CURRENCY_CHOICES, blank=True, default=CURRENCY_KRW
    )
    superhost = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.all().get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Passsword is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignupForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["first_name", "last_name", "email"]

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Comfirm Password")

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password does not match")
        else:
            return password1

    def save(self):
        user = super().save(commit=False)
        user.username = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.set_password(password)
        user.save()

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView
from . import forms
from . import models

# Create your views here.
# render the html


class LoginView(FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    # def get(self, request):
    #     form = forms.LoginForm(initial={"email": "xofla002@gmail.com"})
    #     return render(request, "users/login.html", {"form": form})

    # def post(self, request):
    #     form = forms.LoginForm(request.POST)

    #     if form.is_valid():
    #         email = form.cleaned_data.get("email")
    #         password = form.cleaned_data.get("password")
    #         user = authenticate(request, username=email, password=password)
    #         if user is not None:
    #             login(request, user)
    #             return redirect(reverse("core:home"))
    #     return render(request, "users/login.html", {"form": form})


def LogoutView(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignupView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy("core:home")

    initial = {
        "first_name": "Jo",
        "last_name": "munlak",
        "email": "example@example.com",
    }

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.pk == context["user_obj"].pk:
            context["is_myself"] = True
        else:
            context["is_myself"] = False
        return context


class UpdateUserView(UpdateView):
    model = models.User
    fields = [
        "bio",
        "avatar",
        "gender",
        "birthdate",
        "language",
        "currency",
        "first_name",
        "last_name",
    ]
    template_name = "users/update_profile.html"

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        self.object.username = email
        self.object.save()
        return super().form_valid(form)


class UpdatePasswordView(PasswordChangeView):
    template_name = "users/update_password.html"

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
Log In
{% endblock page_title %}


{% block content %}
<form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{form.as_p}}
    <button>Login</button>
</form>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
Sign up
{% endblock page_title %}


{% block content %}
<form method="POST" action="{% url 'users:signup' %}">
    {% csrf_token %}
    
    {{form.as_p}}
    
    <button>Sign up</button>
</form>
{% endblock content %}

templates/users/update_password.html
{% extends "base.html" %}

{% block page_title %}
Update Password
{% endblock page_title %}


{% block content %}
<form method="POST" action="{% url 'users:password' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button>Save</button>
</form>
{% endblock content %}

templates/users/update_profile.html
{% extends "base.html" %}

{% block page_title %}
Update Profile
{% endblock page_title %}


{% block content %}
<form method="POST" action="{% url 'users:update' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button>Save</button>
</form>


{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}Profile{% endblock page_title %}


{% block content %}
<div>
    <div>
        {% if user_obj.avatar %}
        <img src="{{user_obj.avatar.url}}">
        {% else %}
        <span>{{user_obj.first_name|first}}</span>
        {% endif %}
    </div>


    <h3>{{user_obj.username}}</h3>
    <h4>{{user_obj.first_name}} {{user_obj.last_name}}</h4>
</div>
<div>
    {% if is_myself %}
    <a href="{% url 'users:update' %}">Edit Profile</a>
    {% endif %}
</div>

{% if user_obj.rooms.count > 0 %}
    <div>
        <h3>
            {{user_obj.last_name}}'s Rooms
        </h3>
        <ul>
            {% for room in user_obj.rooms.all %}
                <li>{{room.name}}</li>
            {% endfor %}
        </ul>   
    </div>
{% endif %}

{% endblock content %}